# Generated by Django 4.2.5 on 2023-11-15 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_label', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='auther',
            new_name='author',
        ),
    ]
